info_bitsat_score_analysis:-
    nl,write("BITSAT score Analysis:               BITSAT-2019"),
    nl,write("No of Candidates with score >=400:       235"),
    nl,write("No of Candidates with score >=350:       1790"),
    nl,write("No of Candidates with score >=300:       6328"),
    nl,write("No of Candidates with score >=250:       15563"),
    nl,write("No of Candidates with score >=200:       29460"),
    nl.


info_application_procedure:-
    nl,write(" ---- Application procedure ---- "),
    nl,write("Deadline to apply online for BITSAT-2020 ==> 11th May 2020 (5.00 pm)"),
    nl,write("Test city allotment and announcement to candidates ==> 1st July 2020"),
    nl,write("Candidates to reserve Test date and slot ==> 9th Sept 2020 (11.00am) – 10th Sept 2020 (5.00pm)"),
    nl,write("Candidates to download the Hall tickets with instructions ==> 13th Sept 2020 (11.00am) -23rd Sept 2020 (1.00pm)"),
    nl,write("BITSAT Online tests ==> 16th Sept 2020 – 18th Sept 2020 & 21st Sept 2020 – 23rd Sept 2020"),
    nl,write("Apply for admission with 12th Board marks and Preferences ==> Sept 19-29, 2020"),
    nl,write("Correction in submitted preferences (if any) by the candidates through edit window ==> Sept 30, 2020 (5 PM)"),
    nl,write("Admit list and Wait list announcement post Iteration I ==> October 5, 2020 (5 PM)"),
    nl,write("Deadline for payment of fee/advance fees ==> October 12, 2020 (5 PM)"),
    nl,write("Announcement of admission assignment after Iteration II ==> October 15, 2020 (5 PM)"),
    nl,write("Deadline for payment of balance fees by candidates selected for admission from the waiting list in II iteration. ==> October 19, 2020 (5 PM)"),
    nl,write("Deadline for candidates who wish to submit Withdrawal request online using online credentials ==> October 20, 2020 (5 PM)"),
    nl,write("Announcement of admission assignment after Iteration III. ==> October 23, 2020 (5 PM)"),
    nl,write("Deadline for payment of balance fees by candidates selected for admission from waiting list in III iteration. ==> October 28, 2020 (5 PM)"),
    nl,write("Completion of FD Admission formalities with respect to allotted campuses by the candidates selected for admission in Iterations I-III and verification of their documents (through online mode) ==> Oct 30, 2020 (5 PM)"),
    nl,write("Freshmen Orientation Program by the respective Campuses (through online mode) ==> Oct 30, 2020 (5 PM)"),
    nl,write("Announcement of admission assignment after Iteration IV. ==> October 31, 2020 (5 PM)"),
    nl,write("Registration of Courses for First Semester 2020-21 at respective Campuses. Separate announcement by the respective Campus (through online mode). ==> Nov 02, 2020 (5PM)"),
    nl,write("Classwork begins as per the registration of courses (through online mode) ==> Nov 03, 2020 (5PM)"),
    nl,write("Completion of FD Admission formalities with respect to allotted campuses by the candidates selected for admission in Iteration IV and verification of their documents (through online mode) ==> Nov 09, 2020 (5PM)"),
    nl,write("Announcement of admission assignment after Iteration V ==> Nov 11, 2020 (5PM)"),
    nl,write("Completion of FD Admission formalities with respect to allotted campuses by the candidates selected for admission in Iteration V and verification of their documents (through online mode) ==> Nov 13, 2020 (5PM)"),
    nl,write("Announcement of admission assignment after Iteration VI (if required) ==> Nov 17, 2020 (5PM)"),
    nl,write("Completion of FD Admission formalities with respect to allotted campuses by the candidates selected for admission in Iteration VI and verification of their documents (through online mode). ==> Nov 20, 2020 (5PM)"),
    nl,write(" ------------------------------- "),
    nl.

info_scholarship:-
    nl,write(" ---- Schlorship ----"),
    nl,write("Top 1% of students to be awarded 100% scholarship under Institute’s own merit award scheme"),
    nl,write("Top 2% of students to be awarded 40% scholarship under Institute’s own merit award scheme"),
    nl,write("3% of students awarded 80% scholarship under Institute’s own merit-cum-need awards scheme"),
    nl,write("6% of students awarded 40% scholarship under Institute’s own merit-cum-need awards scheme"),
    nl,write("12% of students awarded 25% scholarship under Institute’s own merit-cum-need awards scheme"),
    nl,write("6% of students awarded 15% scholarship under Institute’s own merit-cum-need awards scheme"),
    nl,write(" ------------------------------- "),
    nl.

info_admission_procedure:-
    nl,write(" ---- Admission procedure ---- "),
    nl,write("Students who are appearing for 12th class examination in 2020 or who have passed"),
    nl,write("12th Examination in 2019 only are eligible to appear in the BITSAT-2020 test. Students"),
    nl,write("who have passed 12th examination in 2018 or earlier are NOT eligible to appear in BITSAT2020."),
    nl,write("Students who are presently studying in BITS at any of its campuses are not eligible to"),
    nl,write("appear in BITSAT-2020."),
    nl,write("Admissions will be made purely on merit. The merit position of the candidate for admission"),
    nl,write("will be based on the score obtained by the candidate in the BITSAT-2020. However, their"),
    nl,write("eligibility for admission is subject to fulfilling the requirement of minimum marks in 12th"),
    nl,write("examination, as mentioned above. The Institute considers only the latest performance"),
    nl,write("through a public examination for admission. If the results of the latest examination are not"),
    nl,write("available within the due date for submission of application, the candidate will not be"),
    nl,write("considered even if there are some earlier performances of 12th class or its equivalent or any"),
    nl,write("higher examination available with him/her. If a candidate has taken more than one attempt"),
    nl,write("in 12th class or its equivalent, only his latest performance is considered, provided this"),
    nl,write("attempt has been for the full component of subjects/courses prescribed."),
    nl,write(" ------------------------------- "),
    nl.
